### ISSUE TITLE
Uploading errors in OpenIMU330BI project

### ISSUE THREAD

**Issue by AndreyBondarev** [Aceinna/platform-aceinna_imu#12]
[ApplicationUploadingError.docx](https://github.com/Aceinna/platform-aceinna_imu/files/3691724/ApplicationUploadingError.docx)

**Comment by valeros** [comment]
Can you please describe under what conditions that errors happen? Could you also please try the latest `OpenIMU330BI` board from this repository?

**Comment by AndreyBondarev** [comment]
I tried latest board file and I see next message while trying to upload binary image:

Uploading .pio\build\imu330\firmware.bin
GNU MCU Eclipse 64-bits Open On-Chip Debugger 0.10.0+dev-00392-gbe9ef0b0 (2018-01-12-15:03)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
debug_level: 1
hla_swd
adapter speed: 500 kHz
adapter_nsrst_delay: 100
none separate
adapter speed: 480 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x080011cc msp: 0x2000ff00
adapter speed: 4000 kHz
** Programming Started **
auto erase enabled
Error: couldn't open .piuildimu330
                                  irmware.bin
embedded:startup.tcl:476: Error: ** Programming Failed **
in procedure 'program' 
in procedure 'program_error' called at file "embedded:startup.tcl", line 532
at file "embedded:startup.tcl", line 476
*** [upload] Error 1

The messages from attached file happened not on my PC.
Note the OOCD version (I think that this is downgraded one)

**Comment by valeros** [comment]
> Note the OOCD version (I think that this is downgraded one)

I'm not completely sure that this issue is related to the OOCD. What Windows version was installed on that machine? I tried both Win8, Win10 and the latest platform uploads firmware without issues.

**Comment by valeros** [comment]
Could you please update the platform to the latest (run `pio update`  from the terminal windows in IDE) and try to upload the firmware again. If the problem persists will it be possible to provide a TeamViewer session on that machine? Thanks!

**Comment by AndreyBondarev** [comment]
HI Valerii

It helped but I needed to change “offset_adress” to 0x08000000 in board file.
Without “offset_address” variable it did not work.

Also with this new version I see duplicates in debug menu:
[cid:image001.jpg@01D57E80.F26FBB20]

And one choice (PIO Debug (IMU)) is working but another is not.
Also as you can see debug watch variables remain in the list but they are from different project/session.

Thank you.

Andrey

**Comment by valeros** [comment]
> It helped but I needed to change “offset_adress” to 0x08000000 in board file.

`0x08000000` is default value in case when `offset_adress` is not set in the board manifest, so it shouldn't be a problem if you are using the latest platform from the development branch. 

>Also with this new version I see duplicates in debug menu:
[cid:image001.jpg@01D57E80.F26FBB20]

The image is not visible here, could you please reattach the screenshot to your comment directly?

**Comment by AndreyBondarev** [comment]
![DoubleDebugOptions](https://user-images.githubusercontent.com/35466478/66506615-8b95a900-ea82-11e9-9fc8-ab5ccae8f492.png)
Without this option in board file loader tried to upload image from address 0x00000000.
Also I do not see double debug options any more.  Maybe it was some glitch

**Comment by valeros** [comment]
Are you sure you're using the latest platform from this repository? Please run `pio platform list` in terminal and paste the info here.
Thanks!

**Comment by AndreyBondarev** [comment]
PS C:\Users\aceinna\Documents\platformio\NewCodeStructure\master\imu_architecture_update\Applications\IMU383\IMU> pio platform list
aceinna_imu ~ Aceinna IMU
=========================
Open-source, embedded development platform for Aceinna IMU hardware. Run custom algorithms and navigation code on Aceinna IMU/INS hardware.

Home: https://github.com/aceinna/platform-aceinna_imu
Packages: tool-jlink, tool-openocd, toolchain-gccarmnoneeabi
Version: 1.2.0

PS C:\Users\aceinna\Documents\platformio\NewCodeStructure\master\imu_architecture_update\Applications\IMU383\IMU>

**Comment by valeros** [comment]
So you are using the latest release, but not the latest revision. Could you please try to specify the following platform in your `platformio.ini`:
```
platform = https://github.com/Aceinna/platform-aceinna_imu.git
```

**Comment by AndreyBondarev** [comment]
This seems to be working. Thanks. I guess it will get into next release?

**Comment by ivankravets** [comment]
1.2.1 is out https://github.com/Aceinna/platform-aceinna_imu/releases/tag/v1.2.1
