### ISSUE TITLE
Incorrect upload offset address

### ISSUE THREAD

**Issue by ivankravets** [Aceinna/platform-aceinna_imu#13]
Unknown option in https://github.com/Aceinna/platform-aceinna_imu/blob/develop/boards/OpenRTK.json#L29

The valid is `offset_address`, see https://github.com/Aceinna/platform-aceinna_imu/blob/develop/builder/main.py#L188

**Comment by AndreyBondarev** [comment]
I fixed it

**Comment by ivankravets** [comment]
Thank you too!
