### ISSUE TITLE
Incompatible board frameworks

### ISSUE THREAD

**Issue by ivankravets** [Aceinna/platform-aceinna_imu#14]
A few boards have incompatible frameworks:
- https://github.com/Aceinna/platform-aceinna_imu/blob/develop/boards/OpenRTK.json#L23

Please check the others. As I understand, IMU uses FreeRTOS which is bundled into aceinna library. So, please keep `"frameworks": []` for ALL boards. Thanks!

Example https://github.com/Aceinna/platform-aceinna_imu/blob/develop/boards/OpenIMU300.json#L23

**Comment by AndreyBondarev** [comment]
So, should I use "frameworks": [ ] for all boards?
I guess   "frameworks": [ "mbed", "stm32cube" ] is legacy thing? These new files came from our other team and I just uploaded them without changes.

**Comment by ivankravets** [comment]
Yes, please use `"frameworks": []` for all boards.

**Comment by AndreyBondarev** [comment]
Thanks. I fixed it
