### ISSUE TITLE
Including "BitStatus.h" instead of "BITStatus.h"

### ISSUE THREAD

**Issue by ManMan88** [Aceinna/platform-aceinna_imu#9]
The INS and VG_AHRS examples include a `UserAlgorithm.c` file which has the following include:
`#include "BitStatus.h"`

I think this is a mistake as it gives a build error.
Shouldn't it be:
`#include "BITStatus.h"`

**Comment by pioplus** [comment]
Thanks for PR! https://github.com/Aceinna/platform-aceinna_imu/pull/10
